name: Publish docker images

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        id: download
        run: |
          gh release download -D /tmp/binaries ${{github.ref_name}}
          
          echo ::set-output name=binary-directory::/tmp/binaries
          
          echo "::group::Downloaded"
          ls -al /tmp/binaries
          echo "::endgroup::"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/metadata-action@v4
        id: meta
        with:
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          images: cucumber/json-formatter

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          push: true
          platforms: |
            linux/386
            linux/arm
            linux/amd64
            linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-contexts: |
            binaries=${{ steps.download.outputs.binary-directory }}
