name: Build Go binaries and create Github release

on:
  push:
    branches:
      - main
      - fix/releases
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: make
      - run: |
        gh release create v0.0.0 go/dist/*
