name: test

on:
  push:
    branches:
      - main
      - fix/working-ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Make
        run: make