name: test

on:
  push:
    branches:
      - main
      - fix/working-ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: cucumber/cucumber-build:0.12.0

    steps:
      - uses: actions/checkout@v3
      - name: Make
        run: make